home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns=[
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	
	]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views


urlpatterns = [
	path('', include('home.urls')),
#	path('myarts/', include('myarts.urls')),
    path('admin/', admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('register/', user_views.Register.as_view(), name="register"),
]

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):
	return render(request, 'home/home.html')


@login_required
def about(request):
	return render(request, 'home/about.html')

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.urls import reverse_lazy
from .forms import UserRegisterForm
# Create your views here.
class Register(View):
	template = "users/register.html"
	def get(self, request):
		form = UserRegisterForm()
		context={'form':form}
		return render(request, self.template, context)
	def post(self, request):
		form = UserRegisterForm(request.POST)
		if not form.is_valid():
			context={
			'form':form
			}
			return render(request, self.template, context)
		else:
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'{username} has been created successfully')
			return redirect(reverse_lazy('login'))

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'home/main.css' %}">
	{% if title %}
		<title>Change Title - {{ title }}</title>
	{% else %}
		<title>Change Title</title>
	{% endif %}
</head>
<body>

	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'home:home'%}">Web_name</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'home:home'%}">Home</a>

	          <a class="nav-item nav-link" href="{% url 'home:about'%}">About</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if user.is_authenticated %}
	        		<a class="nav-item nav-link" href="#">New</a>
	        		<a class="nav-item nav-link" href="#}">Profile</a>
	        		<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
	        	{% else %}
		          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
		          
		          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
		        {% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% if messages %}
	    		{% for message in messages %}
	    			<div class="alert alert-{{ message.tags}}">	
	    				{{ message }}

	    			</div>
	    		{% endfor %}
	    	{% endif %}
	      	{% block content %}{% endblock %}
	    	
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          
	        </p>
	      </div>
	    </div>
	  </div>
	</main>
	
	 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
</body>
</html>

home/templates/home/about.html
{% extends "base.html" %}
{% block content %}
<h1>About</h1><br>
<p>
<div class="content-section">
	A simple project for authetication <br>
	{{user.username}} : {{user.email}}
	
</div>

</p>
{% endblock content %}

home/templates/home/home.html
{% extends 'base.html' %}
{% block content %}
<div class='content-section'>
	This is home page
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class='content-section'>
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Login</legend>
			{{ form|crispy }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Login</button>
		</div>
	</form>
	<div class="border-top pt-3">
			<small class="text-muted">
			Need an account? <a class="ml-2" href="{% url 'register'%}">Sign Up </a>
			</small>
		</div>

</div>

{% endblock content %}

users/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
<h2>You have been logged out</h2>
<div class="content-section">
	<small class="text-muted">
		<a href="{% url 'login' %}">Log in Again?</a>
	</small>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				{{ form|crispy }}
				
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Signup</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
			Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In </a>
			</small>
		</div>
	</div>
{% endblock content %}